### ISSUE TITLE
Project doesn't compile under windows 

### ISSUE THREAD

**Issue by robotiko** [patrickjahns/esp_rgbww_firmware#3]
19:05:52 ***\* Build of configuration Sming for project RGBCTRLfw ****
make -k all 
OC out/build/libmain2.a
make -C /c/tools/sming/sming/rboot
make[1]: Entering directory `/c/tools/sming/sming/rboot'
CC rboot-stage2a.c
LD /c/Development/esp_rgbww_firmware/out/build/rboot-stage2a.elf
E2 /c/Development/esp_rgbww_firmware/out/build/rboot-hex2a.h
CC rboot.c
LD /c/Development/esp_rgbww_firmware/out/build/rboot.elf
E2 /c/Development/esp_rgbww_firmware/out/firmware/rboot.bin
make[1]: Leaving directory`/c/tools/sming/sming/rboot'
C+ app/application.cpp
In file included from include/user_config.h:29:0,
                 from include/RGBWWCtrl.h:55,
                 from app/application.cpp:23:
c:/tools/sming/sming/system/include/esp_systemapi.h:6:21: fatal error: ets_sys.h: No such file or directory
compilation terminated.
make: **\* [out/build/app/application.o] Error 1
C+ app/ledctrl.cpp
In file included from include/user_config.h:29:0,
                 from include/RGBWWCtrl.h:55,
                 from app/ledctrl.cpp:22:
c:/tools/sming/sming/system/include/esp_systemapi.h:6:21: fatal error: ets_sys.h: No such file or directory
compilation terminated.
make: **\* [out/build/app/ledctrl.o] Error 1
C+ app/mqtt.cpp
In file included from include/user_config.h:29:0,
                 from include/RGBWWCtrl.h:55,
                 from app/mqtt.cpp:22:
c:/tools/sming/sming/system/include/esp_systemapi.h:6:21: fatal error: ets_sys.h: No such file or directory
compilation terminated.
make: **\* [out/build/app/mqtt.o] Error 1
C+ app/networking.cpp
In file included from include/user_config.h:29:0,
                 from include/RGBWWCtrl.h:55,
                 from app/networking.cpp:22:
c:/tools/sming/sming/system/include/esp_systemapi.h:6:21: fatal error: ets_sys.h: No such file or directory
compilation terminated.
make: **\* [out/build/app/networking.o] Error 1
C+ app/otaupdate.cpp
In file included from include/user_config.h:29:0,
                 from include/RGBWWCtrl.h:55,
                 from app/otaupdate.cpp:22:
c:/tools/sming/sming/system/include/esp_systemapi.h:6:21: fatal error: ets_sys.h: No such file or directory
compilation terminated.
make: **\* [out/build/app/otaupdate.o] Error 1
C+ app/tcpserver.cpp
In file included from include/user_config.h:29:0,
                 from include/RGBWWCtrl.h:55,
                 from app/tcpserver.cpp:22:
c:/tools/sming/sming/system/include/esp_systemapi.h:6:21: fatal error: ets_sys.h: No such file or directory
compilation terminated.
make: **\* [out/build/app/tcpserver.o] Error 1
C+ app/udpserver.cpp
In file included from include/user_config.h:29:0,
                 from include/RGBWWCtrl.h:55,
                 from app/udpserver.cpp:22:
c:/tools/sming/sming/system/include/esp_systemapi.h:6:21: fatal error: ets_sys.h: No such file or directory
compilation terminated.
make: **\* [out/build/app/udpserver.o] Error 1
C+ app/webserver.cpp
In file included from include/user_config.h:29:0,
                 from include/RGBWWCtrl.h:55,
                 from app/webserver.cpp:22:
c:/tools/sming/sming/system/include/esp_systemapi.h:6:21: fatal error: ets_sys.h: No such file or directory
compilation terminated.
make: **\* [out/build/app/webserver.o] Error 1
CC /c/tools/sming/sming/rboot/appcode/rboot-api.c
c:/tools/sming/sming/rboot/appcode/rboot-api.c:10:21: fatal error: c_types.h: No such file or directory
compilation terminated.
make: **\* [out/build//c/tools/sming/sming/rboot/appcode/rboot-api.o] Error 1
CC /c/tools/sming/sming/rboot/appcode/rboot-bigflash.c
In file included from c:/tools/sming/sming/system/include/rboot-integration.h:11:0,
                 from c:/tools/sming/sming/rboot/appcode/rboot-bigflash.c:9:
c:/tools/sming/sming/system/include/esp_systemapi.h:6:21: fatal error: ets_sys.h: No such file or directory
compilation terminated.
make: **\* [out/build//c/tools/sming/sming/rboot/appcode/rboot-bigflash.o] Error 1
Checking for spiffs files
No files found in ./webapp.
Creating empty out/firmware/spiff_rom.bin
Creating rom 'out/firmware/spiff_rom.bin' of size 0xf4240 (1000000) bytes.
Creating empty filesystem.
make: Target `all' not remade because of errors.

**Comment by patrickjahns** [comment]
To me this looks like that some path variables are not set correctly - specifically where to find the esp_sdk. Please check your windows environment vars as well as the environment vars inside eclipse - it might be that some are not correctly set
